#!/bin/bash

RUN_DIR=/var/vcap/sys/run/openstack_registry
LOG_DIR=/var/vcap/sys/log/openstack_registry
PIDFILE=$RUN_DIR/openstack_registry.pid

export PATH=/var/vcap/packages/ruby/bin:$PATH

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    exec /var/vcap/packages/openstack_registry/bosh/openstack_registry/bin/openstack_registry \
      -c /var/vcap/jobs/openstack_registry/config/openstack_registry.yml \
      >>$LOG_DIR/openstack_registry.stdout.log 2>>$LOG_DIR/openstack_registry.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: openstack_registry_ctl {start|stop}" ;;
esac
exit 0
